// frontend-svelte/src/routes/login/+page.svelte
<script>
	import { signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup, updateProfile } from 'firebase/auth';
	import { auth, googleProvider } from '$lib/config/firebase.js';
	import { user, loading, error } from '$lib/stores/auth.js';
	import { goto } from '$app/navigation';
	import { redirectIfAuthenticated } from '$lib/utils/auth-guard.js';
	
	let email = '';
	let password = '';
	let isSignUp = false;
	let localError = '';
	let successMessage = '';
	
	// Redirect if already authenticated
	$: if ($user) {
		redirectIfAuthenticated();
	}

	async function handleSubmit() {
		if (!email || !password) {
			localError = 'Please fill in all fields';
			return;
		}

		try {
			loading.set(true);
			localError = '';
			successMessage = '';
			
			if (isSignUp) {
				await createUserWithEmailAndPassword(auth, email, password);
				successMessage = 'Account created successfully! Redirecting...';
			} else {
				await signInWithEmailAndPassword(auth, email, password);
				successMessage = 'Login successful! Redirecting...';
			}
			
			// Small delay to show success message
			setTimeout(() => {
				goto('/');
			}, 1000);
		} catch (err) {
			// Make error messages more user-friendly
			if (err.code === 'auth/user-not-found' || err.code === 'auth/wrong-password') {
				localError = 'Invalid email or password';
			} else if (err.code === 'auth/email-already-in-use') {
				localError = 'An account with this email already exists';
			} else if (err.code === 'auth/weak-password') {
				localError = 'Password should be at least 6 characters';
			} else if (err.code === 'auth/invalid-email') {
				localError = 'Invalid email address';
			} else {
				localError = err.message || 'Authentication failed';
			}
			console.error('Auth error:', err);
		} finally {
			loading.set(false);
		}
	}

	function toggleMode() {
		isSignUp = !isSignUp;
		localError = '';
		successMessage = '';
	}

	async function handleSocialLogin(provider, providerName) {
		try {
			loading.set(true);
			localError = '';
			successMessage = '';
			
			const result = await signInWithPopup(auth, provider);
			const user = result.user;
			
			// Extract user information from the social login
			const userInfo = {
				uid: user.uid,
				email: user.email,
				displayName: user.displayName,
				photoURL: user.photoURL,
				phoneNumber: user.phoneNumber,
				providerId: result.providerId
			};
			
			// Additional user info handling can be added here if needed
			
			successMessage = `${providerName} login successful! Redirecting...`;
			console.log('Social login user info:', userInfo);
			
			// Small delay to show success message
			setTimeout(() => {
				goto('/');
			}, 1000);
		} catch (err) {
			console.error(`${providerName} login error:`, err);
			
			// Handle specific social login errors
			if (err.code === 'auth/popup-closed-by-user') {
				localError = 'Login was cancelled';
			} else if (err.code === 'auth/popup-blocked') {
				localError = 'Popup was blocked by your browser. Please allow popups and try again.';
			} else if (err.code === 'auth/account-exists-with-different-credential') {
				localError = 'An account already exists with the same email address but different sign-in credentials.';
			} else if (err.code === 'auth/auth-domain-config-required') {
				localError = 'Social login is not properly configured. Please contact support.';
			} else {
				localError = `${providerName} login failed: ${err.message}`;
			}
		} finally {
			loading.set(false);
		}
	}

	async function handleGoogleLogin() {
		await handleSocialLogin(googleProvider, 'Google');
	}
</script>

<svelte:head>
	<title>{isSignUp ? 'Sign Up' : 'Login'} - ForkFlix</title>
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 relative overflow-hidden">
	<!-- Background decoration -->
	<div class="absolute inset-0 opacity-30">
		<div class="absolute top-20 left-20 w-72 h-72 bg-blue-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse"></div>
		<div class="absolute top-40 right-20 w-96 h-96 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse" style="animation-delay: 2s;"></div>
		<div class="absolute bottom-20 left-40 w-80 h-80 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse" style="animation-delay: 4s;"></div>
	</div>
	
	<div class="sm:mx-auto sm:w-full sm:max-w-md relative z-10">
		<div class="text-center">
			<h1 class="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-4">🍴 ForkFlix</h1>
			<h2 class="text-3xl font-bold text-gray-900 mb-2">
				{isSignUp ? 'Create your account' : 'Welcome back!'}
			</h2>
			<p class="text-gray-600 text-lg">
				{isSignUp ? 'Start organizing your recipe videos' : 'Sign in to your recipe collection'}
			</p>
		</div>
	</div>

	<div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md relative z-10">
		<div class="bg-white/90 backdrop-blur-md py-10 px-6 shadow-2xl rounded-2xl border border-white/20">
			<form on:submit|preventDefault={handleSubmit} class="space-y-8">
				{#if localError}
					<div class="bg-gradient-to-r from-red-50 to-pink-50 border border-red-200 rounded-xl p-4 shadow-lg">
						<div class="flex items-center space-x-3">
							<div class="text-xl">⚠️</div>
							<p class="text-red-700 font-medium">{localError}</p>
						</div>
					</div>
				{/if}

				{#if successMessage}
					<div class="bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-xl p-4 shadow-lg">
						<div class="flex items-center space-x-3">
							<div class="text-xl">✓</div>
							<p class="text-green-700 font-medium">{successMessage}</p>
						</div>
					</div>
				{/if}

				<div>
					<label for="email" class="block text-sm font-semibold text-gray-700 mb-3">
						📧 Email address
					</label>
					<input
						id="email"
						type="email"
						bind:value={email}
						required
						class="w-full px-4 py-4 bg-white/70 backdrop-blur-sm border border-gray-200 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900 placeholder-gray-500 shadow-lg transition-all duration-200"
						placeholder="your@email.com"
					>
				</div>

				<div>
					<label for="password" class="block text-sm font-semibold text-gray-700 mb-3">
						🔒 Password
					</label>
					<input
						id="password"
						type="password"
						bind:value={password}
						required
						class="w-full px-4 py-4 bg-white/70 backdrop-blur-sm border border-gray-200 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900 placeholder-gray-500 shadow-lg transition-all duration-200"
						placeholder="••••••••"
					>
				</div>

				<div>
					<button
						type="submit"
						disabled={$loading}
						class="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-2xl font-bold text-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-200 transform hover:scale-[1.02] shadow-xl disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
					>
						<span class="flex items-center justify-center space-x-3">
							{#if $loading}
								<div class="inline-block animate-spin rounded-full h-5 w-5 border-2 border-white border-b-transparent"></div>
							{:else}
								<span>{isSignUp ? '✨ Create Account' : '🚀 Sign In'}</span>
							{/if}
						</span>
					</button>
				</div>
			</form>

			<!-- Social Login Section -->
			<div class="mt-8">
				<div class="relative">
					<div class="absolute inset-0 flex items-center">
						<div class="w-full border-t border-gray-300"></div>
					</div>
					<div class="relative flex justify-center text-sm">
						<span class="px-4 bg-white text-gray-500 font-medium">Or continue with</span>
					</div>
				</div>

				<div class="mt-6">
					<!-- Google Login Button -->
					<button
						type="button"
						on:click={handleGoogleLogin}
						disabled={$loading}
						class="w-full inline-flex justify-center items-center py-3 px-4 border border-gray-300 rounded-xl shadow-sm bg-white/80 backdrop-blur-sm text-sm font-medium text-gray-700 hover:bg-gray-50 hover:border-gray-400 transition-all duration-200 transform hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
					>
						<svg class="w-5 h-5 mr-2" viewBox="0 0 24 24">
							<path fill="#4285f4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
							<path fill="#34a853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
							<path fill="#fbbc05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
							<path fill="#ea4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
						</svg>
						Continue with Google
					</button>
				</div>
			</div>

			<div class="mt-8">
				<div class="text-center">
					<button
						type="button"
						on:click={toggleMode}
						class="font-semibold text-blue-600 hover:text-purple-600 transition-colors duration-200 text-lg"
					>
						{isSignUp 
							? '👋 Already have an account? Sign in' 
							: "🎆 Don't have an account? Sign up"
						}
					</button>
				</div>
			</div>

			<div class="mt-6">
				<div class="text-center">
					<button
						type="button"
						on:click={() => goto('/landing')}
						class="text-gray-600 hover:text-blue-600 transition-colors duration-200 font-medium"
					>
						← Back to landing page
					</button>
				</div>
			</div>
		</div>
	</div>
</div>

// frontend/src/pages/Login.tsx
import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, Link } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import Button from '../components/common/Button';
import ErrorBanner from '../components/common/ErrorBanner';
import Loading from '../components/common/Loading';

/**
 * Login form data interface
 */
interface LoginFormData {
  email: string;
  password: string;
  rememberMe: boolean;
}

/**
 * Login page component with form validation and Firebase auth integration
 */
const Login: React.FC = () => {
  const { login, user, loading, error, clearError } = useApp();
  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    setError,
  } = useForm<LoginFormData>({
    defaultValues: {
      email: '',
      password: '',
      rememberMe: false,
    },
  });

  // Redirect if already logged in
  useEffect(() => {
    if (user) {
      navigate('/', { replace: true });
    }
  }, [user, navigate]);

  // Set page title
  useEffect(() => {
    document.title = 'Login - Recipe Reel Manager';
  }, []);

  // Handle form submission
  const onSubmit = async (data: LoginFormData) => {
    try {
      clearError();
      await login(data.email, data.password);
    } catch (error: any) {
      // Handle specific Firebase auth errors
      let errorMessage = 'Failed to sign in. Please try again.';
      
      if (error?.code) {
        switch (error.code) {
          case 'auth/user-not-found':
            errorMessage = 'No account found with this email address.';
            setError('email', { type: 'manual', message: errorMessage });
            break;
          case 'auth/wrong-password':
            errorMessage = 'Incorrect password. Please try again.';
            setError('password', { type: 'manual', message: errorMessage });
            break;
          case 'auth/invalid-email':
            errorMessage = 'Invalid email address format.';
            setError('email', { type: 'manual', message: errorMessage });
            break;
          case 'auth/user-disabled':
            errorMessage = 'This account has been disabled.';
            break;
          case 'auth/too-many-requests':
            errorMessage = 'Too many failed attempts. Please try again later.';
            break;
          default:
            break;
        }
      }
    }
  };

  // Toggle password visibility
  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  // Handle social login (placeholder)
  const handleGoogleLogin = () => {
    // TODO: Implement Google OAuth login
    console.log('Google login clicked - to be implemented');
  };

  // Show loading spinner during auth state check
  if (loading.isLoading && !isSubmitting) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
        <Loading size="large" message="Checking authentication..." />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        {/* Header */}
        <div className="text-center">
          <div className="mx-auto h-12 w-12 flex items-center justify-center rounded-full bg-gradient-to-r from-primary-500 to-secondary-500">
            <svg className="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
          </div>
          <h2 className="mt-6 text-3xl font-extrabold text-gray-900 dark:text-white">
            Welcome back
          </h2>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Sign in to your Recipe Reel Manager account
          </p>
        </div>

        {/* Error Banner */}
        {error.hasError && (
          <ErrorBanner
            variant="error"
            message={error.message || 'An error occurred during login'}
            dismissible
            onDismiss={clearError}
            className="mb-6"
          />
        )}

        {/* Login Form */}
        <form className="mt-8 space-y-6" onSubmit={handleSubmit(onSubmit)}>
          <div className="space-y-4">
            {/* Email Field */}
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Email address
              </label>
              <div className="relative">
                <input
                  {...register('email', {
                    required: 'Email is required',
                    pattern: {
                      value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                      message: 'Invalid email address format',
                    },
                  })}
                  type="email"
                  autoComplete="email"
                  className={`
                    appearance-none relative block w-full px-3 py-2 border rounded-lg
                    placeholder-gray-500 text-gray-900 dark:text-white dark:bg-gray-800
                    focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500
                    dark:border-gray-600 dark:placeholder-gray-400
                    ${errors.email 
                      ? 'border-red-300 dark:border-red-600 focus:ring-red-500 focus:border-red-500' 
                      : 'border-gray-300'
                    }
                  `}
                  placeholder="Enter your email"
                />
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center">
                  <svg className="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
                  </svg>
                </div>
              </div>
              {errors.email && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.email.message}</p>
              )}
            </div>

            {/* Password Field */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Password
              </label>
              <div className="relative">
                <input
                  {...register('password', {
                    required: 'Password is required',
                    minLength: {
                      value: 6,
                      message: 'Password must be at least 6 characters',
                    },
                  })}
                  type={showPassword ? 'text' : 'password'}
                  autoComplete="current-password"
                  className={`
                    appearance-none relative block w-full px-3 py-2 pr-10 border rounded-lg
                    placeholder-gray-500 text-gray-900 dark:text-white dark:bg-gray-800
                    focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500
                    dark:border-gray-600 dark:placeholder-gray-400
                    ${errors.password 
                      ? 'border-red-300 dark:border-red-600 focus:ring-red-500 focus:border-red-500' 
                      : 'border-gray-300'
                    }
                  `}
                  placeholder="Enter your password"
                />
                <button
                  type="button"
                  onClick={togglePasswordVisibility}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                >
                  {showPassword ? (
                    <svg className="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L12 12m-2.122-2.122L7.76 7.76m0 0L5.636 5.636m0 0L12 12m0 0l7.071-7.071M12 12l-7.071 7.071" />
                    </svg>
                  ) : (
                    <svg className="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                  )}
                </button>
              </div>
              {errors.password && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.password.message}</p>
              )}
            </div>
          </div>

          {/* Remember Me & Forgot Password */}
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                {...register('rememberMe')}
                type="checkbox"
                className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded dark:border-gray-600 dark:bg-gray-800"
              />
              <label htmlFor="rememberMe" className="ml-2 block text-sm text-gray-700 dark:text-gray-300">
                Remember me
              </label>
            </div>

            <div className="text-sm">
              <Link
                to="/forgot-password"
                className="font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300"
              >
                Forgot your password?
              </Link>
            </div>
          </div>

          {/* Submit Button */}
          <Button
            type="submit"
            variant="primary"
            size="lg"
            fullWidth
            loading={isSubmitting}
            loadingText="Signing in..."
            disabled={isSubmitting}
          >
            Sign in
          </Button>

          {/* Divider */}
          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-300 dark:border-gray-600" />
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-gray-50 dark:bg-gray-900 text-gray-500 dark:text-gray-400">Or continue with</span>
            </div>
          </div>

          {/* Social Login */}
          <Button
            type="button"
            variant="outline"
            size="lg"
            fullWidth
            onClick={handleGoogleLogin}
            icon={
              <svg className="w-5 h-5" viewBox="0 0 24 24">
                <path
                  fill="currentColor"
                  d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                />
                <path
                  fill="currentColor"
                  d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                />
                <path
                  fill="currentColor"
                  d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                />
                <path
                  fill="currentColor"
                  d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                />
              </svg>
            }
          >
            Sign in with Google
          </Button>

          {/* Sign Up Link */}
          <div className="text-center">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Don't have an account?{' '}
              <Link
                to="/signup"
                className="font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300"
              >
                Sign up now
              </Link>
            </p>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;
