// frontend/src/components/common/Modal.tsx
import React, { useEffect, useRef, useCallback } from 'react';
import { createPortal } from 'react-dom';

/**
 * Modal size types
 */
export type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full';

/**
 * Props for the Modal component
 */
export interface ModalProps {
  /** Whether the modal is open */
  isOpen: boolean;
  /** Callback when modal should be closed */
  onClose: () => void;
  /** Modal title */
  title?: string;
  /** Modal size */
  size?: ModalSize;
  /** Whether to show close button */
  showCloseButton?: boolean;
  /** Whether to close on backdrop click */
  closeOnBackdropClick?: boolean;
  /** Whether to close on escape key */
  closeOnEscape?: boolean;
  /** Additional CSS classes for the modal */
  className?: string;
  /** Additional CSS classes for the backdrop */
  backdropClassName?: string;
  /** Children content */
  children: React.ReactNode;
  /** Custom header content */
  header?: React.ReactNode;
  /** Custom footer content */
  footer?: React.ReactNode;
}

/**
 * Modal component with backdrop blur, focus trap, and animations
 */
const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  size = 'md',
  showCloseButton = true,
  closeOnBackdropClick = true,
  closeOnEscape = true,
  className = '',
  backdropClassName = '',
  children,
  header,
  footer,
}) => {
  const modalRef = useRef<HTMLDivElement>(null);
  const previousActiveElement = useRef<HTMLElement | null>(null);

  // Size classes for the modal
  const sizeClasses = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-4xl',
    full: 'max-w-full mx-4',
  };

  // Handle escape key press
  const handleEscapeKey = useCallback((event: KeyboardEvent) => {
    if (event.key === 'Escape' && closeOnEscape) {
      onClose();
    }
  }, [closeOnEscape, onClose]);

  // Handle backdrop click
  const handleBackdropClick = useCallback((event: React.MouseEvent<HTMLDivElement>) => {
    if (event.target === event.currentTarget && closeOnBackdropClick) {
      onClose();
    }
  }, [closeOnBackdropClick, onClose]);

  // Focus trap implementation
  const handleTabKey = useCallback((event: KeyboardEvent) => {
    if (event.key !== 'Tab' || !modalRef.current) return;

    const focusableElements = modalRef.current.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;

    if (event.shiftKey) {
      if (document.activeElement === firstElement) {
        event.preventDefault();
        lastElement?.focus();
      }
    } else {
      if (document.activeElement === lastElement) {
        event.preventDefault();
        firstElement?.focus();
      }
    }
  }, []);

  // Set up event listeners and focus management
  useEffect(() => {
    if (isOpen) {
      // Store the previously focused element
      previousActiveElement.current = document.activeElement as HTMLElement;
      
      // Add event listeners
      document.addEventListener('keydown', handleEscapeKey);
      document.addEventListener('keydown', handleTabKey);
      
      // Prevent body scroll
      document.body.style.overflow = 'hidden';
      
      // Focus the modal
      setTimeout(() => {
        modalRef.current?.focus();
      }, 100);
    } else {
      // Restore focus to previously focused element
      if (previousActiveElement.current) {
        previousActiveElement.current.focus();
      }
    }

    return () => {
      document.removeEventListener('keydown', handleEscapeKey);
      document.removeEventListener('keydown', handleTabKey);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, handleEscapeKey, handleTabKey]);

  // Don't render if not open
  if (!isOpen) return null;

  // Close button component
  const CloseButton = () => (
    <button
      onClick={onClose}
      className="absolute top-4 right-4 p-2 text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300 transition-colors duration-200 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800"
      aria-label="Close modal"
    >
      <svg
        className="w-5 h-5"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M6 18L18 6M6 6l12 12"
        />
      </svg>
    </button>
  );

  // Modal content
  const modalContent = (
    <div
      className={`fixed inset-0 z-50 flex items-center justify-center p-4 ${backdropClassName}`}
      onClick={handleBackdropClick}
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? 'modal-title' : undefined}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black bg-opacity-50 backdrop-blur-sm transition-opacity duration-300" />
      
      {/* Modal */}
      <div
        ref={modalRef}
        className={`
          relative w-full ${sizeClasses[size]} max-h-[90vh] overflow-y-auto
          bg-white dark:bg-gray-800 rounded-xl shadow-2xl
          transform transition-all duration-300 ease-out
          animate-slide-up
          ${className}
        `}
        tabIndex={-1}
      >
        {/* Close button */}
        {showCloseButton && <CloseButton />}
        
        {/* Header */}
        {(header || title) && (
          <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
            {header || (
              <h2
                id="modal-title"
                className="text-xl font-semibold text-gray-900 dark:text-white pr-8"
              >
                {title}
              </h2>
            )}
          </div>
        )}
        
        {/* Body */}
        <div className="px-6 py-4">
          {children}
        </div>
        
        {/* Footer */}
        {footer && (
          <div className="px-6 py-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 rounded-b-xl">
            {footer}
          </div>
        )}
      </div>
    </div>
  );

  // Render modal using portal
  return createPortal(modalContent, document.body);
};

export default Modal;

// frontend-svelte/src/lib/components/Modal.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import Button from './Button.svelte';
  
  const dispatch = createEventDispatcher();
  
  export let open = false;
  export let title = '';
  export let confirmText = 'Confirm';
  export let cancelText = 'Cancel';
  export let confirmVariant = 'primary';
  export let loading = false;
  export let size = 'md'; // sm, md, lg
  
  function handleClose() {
    if (loading) return; // Prevent closing while loading
    dispatch('close');
  }
  
  function handleConfirm() {
    dispatch('confirm');
  }
  
  function handleCancel() {
    if (loading) return; // Prevent canceling while loading
    dispatch('cancel');
    handleClose();
  }
  
  function handleKeydown(event) {
    if (event.key === 'Escape' && !loading) {
      handleClose();
    }
  }
  
  function handleBackdropClick(event) {
    if (event.target === event.currentTarget && !loading) {
      handleClose();
    }
  }
  
  $: sizeClasses = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl'
  };
</script>

{#if open}
  <!-- Backdrop -->
  <div 
    class="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
    on:click={handleBackdropClick}
    on:keydown={handleKeydown}
    role="dialog"
    aria-modal="true"
    aria-labelledby="modal-title"
  >
    <!-- Modal -->
    <div 
      class="bg-white rounded-2xl shadow-2xl w-full {sizeClasses[size]} transform transition-all duration-200 scale-100"
      class:opacity-50={loading}
      class:pointer-events-none={loading}
    >
      <!-- Header -->
      {#if title}
        <div class="px-6 py-4 border-b border-gray-200">
          <h3 id="modal-title" class="text-lg font-semibold text-gray-900">
            {title}
          </h3>
        </div>
      {/if}
      
      <!-- Content -->
      <div class="px-6 py-4">
        <slot />
      </div>
      
      <!-- Footer -->
      <div class="px-6 py-4 border-t border-gray-200 flex justify-end space-x-3">
        <Button
          variant="outline"
          on:click={handleCancel}
          disabled={loading}
        >
          {cancelText}
        </Button>
        <Button
          variant={confirmVariant}
          on:click={handleConfirm}
          {loading}
        >
          {confirmText}
        </Button>
      </div>
    </div>
  </div>
{/if}

<style>
  /* Ensure modal appears above everything else */
  :global(body:has(.modal-open)) {
    overflow: hidden;
  }
</style>
